"""
Tests for the in-memory History Store and its API endpoints.

Author: Ishaq Muhammad (PXPRGK)
Course: BSc Thesis - ELTE Faculty of Informatics
"""

from datetime import datetime

import pytest

from backend.api.historyStore import HistoryEntry, HistoryStore, MAX_ENTRIES
from backend.api.schemas import (
    AnalysisResponse,
    FeatureSummary,
    VerdictResult,
)


# =============================================================================
# Fixtures
# =============================================================================

def _makeResponse(**overrides) -> AnalysisResponse:
    """Build a minimal valid AnalysisResponse."""
    defaults = dict(
        success=True,
        verdict=VerdictResult(
            isPhishing=False,
            confidenceScore=0.2,
            threatLevel="safe",
            reasons=[],
            recommendation="Looks safe",
        ),
        features=FeatureSummary(),
        analysisTime=100.0,
        analyzedAt=datetime.now(),
    )
    defaults.update(overrides)
    return AnalysisResponse(**defaults)


@pytest.fixture()
def store() -> HistoryStore:
    """Fresh empty store for each test."""
    return HistoryStore(maxEntries=MAX_ENTRIES)


@pytest.fixture()
def smallStore() -> HistoryStore:
    """Store with a small capacity for FIFO testing."""
    return HistoryStore(maxEntries=5)


# =============================================================================
# HistoryEntry Schema
# =============================================================================

class TestHistoryEntry:
    def test_idAutoGenerated(self):
        entry = HistoryEntry(
            content="https://example.com",
            contentType="url",
            response=_makeResponse(),
        )
        assert entry.id
        assert len(entry.id) == 36  # UUID format

    def test_createdAtAutoSet(self):
        entry = HistoryEntry(
            content="test",
            contentType="text",
            response=_makeResponse(),
        )
        assert isinstance(entry.createdAt, datetime)

    def test_uniqueIds(self):
        ids = set()
        for _ in range(20):
            entry = HistoryEntry(
                content="x", contentType="text", response=_makeResponse()
            )
            ids.add(entry.id)
        assert len(ids) == 20


# =============================================================================
# HistoryStore — add / list
# =============================================================================

class TestHistoryStoreAdd:
    def test_addReturnsEntry(self, store: HistoryStore):
        entry = store.add("https://example.com", "url", _makeResponse())
        assert isinstance(entry, HistoryEntry)
        assert entry.content == "https://example.com"
        assert entry.contentType == "url"

    def test_addIncrementsCount(self, store: HistoryStore):
        assert store.count == 0
        store.add("a", "url", _makeResponse())
        assert store.count == 1
        store.add("b", "url", _makeResponse())
        assert store.count == 2

    def test_addFifoEviction(self, smallStore: HistoryStore):
        entries = []
        for i in range(7):
            entries.append(smallStore.add(f"url-{i}", "url", _makeResponse()))
        assert smallStore.count == 5
        remaining = smallStore.list()
        ids = [e.id for e in remaining.entries]
        assert entries[0].id not in ids
        assert entries[1].id not in ids
        assert entries[6].id in ids


class TestHistoryStoreList:
    def test_listEmpty(self, store: HistoryStore):
        result = store.list()
        assert result.entries == []
        assert result.total == 0

    def test_listNewestFirst(self, store: HistoryStore):
        store.add("first", "url", _makeResponse())
        store.add("second", "url", _makeResponse())
        store.add("third", "url", _makeResponse())
        result = store.list()
        assert result.entries[0].content == "third"
        assert result.entries[2].content == "first"

    def test_listWithLimit(self, store: HistoryStore):
        for i in range(10):
            store.add(f"url-{i}", "url", _makeResponse())
        result = store.list(limit=3)
        assert len(result.entries) == 3
        assert result.total == 10

    def test_listWithOffset(self, store: HistoryStore):
        for i in range(5):
            store.add(f"url-{i}", "url", _makeResponse())
        result = store.list(limit=2, offset=2)
        assert len(result.entries) == 2
        assert result.entries[0].content == "url-2"


# =============================================================================
# HistoryStore — get
# =============================================================================

class TestHistoryStoreGet:
    def test_getExisting(self, store: HistoryStore):
        entry = store.add("test", "url", _makeResponse())
        found = store.get(entry.id)
        assert found is not None
        assert found.id == entry.id

    def test_getNonExistent(self, store: HistoryStore):
        assert store.get("non-existent-id") is None


# =============================================================================
# HistoryStore — delete
# =============================================================================

class TestHistoryStoreDelete:
    def test_deleteExisting(self, store: HistoryStore):
        entry = store.add("test", "url", _makeResponse())
        assert store.delete(entry.id) is True
        assert store.count == 0

    def test_deleteNonExistent(self, store: HistoryStore):
        assert store.delete("non-existent-id") is False

    def test_deleteDoesNotAffectOthers(self, store: HistoryStore):
        e1 = store.add("a", "url", _makeResponse())
        e2 = store.add("b", "url", _makeResponse())
        store.delete(e1.id)
        assert store.count == 1
        assert store.get(e2.id) is not None


# =============================================================================
# HistoryStore — clear
# =============================================================================

class TestHistoryStoreClear:
    def test_clearReturnsCount(self, store: HistoryStore):
        for i in range(5):
            store.add(f"url-{i}", "url", _makeResponse())
        removed = store.clear()
        assert removed == 5
        assert store.count == 0

    def test_clearEmptyStore(self, store: HistoryStore):
        assert store.clear() == 0


# =============================================================================
# API Endpoint Tests (via TestClient)
# =============================================================================

class TestHistoryEndpoints:
    """Test history REST endpoints via FastAPI TestClient."""

    @pytest.fixture(autouse=True)
    def _setupClient(self):
        """Import the app and reset the store before each test."""
        from fastapi.testclient import TestClient
        from backend.api.historyStore import historyStore
        from backend.main import app

        historyStore.clear()
        self.client = TestClient(app)
        self.store = historyStore

    def test_listHistoryEmpty(self):
        resp = self.client.get("/api/history")
        assert resp.status_code == 200
        data = resp.json()
        assert data["entries"] == []
        assert data["total"] == 0

    def test_analyzeAutoSavesToHistory(self):
        self.client.post(
            "/api/analyze/url",
            json={"url": "https://example.com"},
        )
        resp = self.client.get("/api/history")
        assert resp.status_code == 200
        data = resp.json()
        assert data["total"] == 1
        assert data["entries"][0]["content"] == "https://example.com"

    def test_getHistoryEntryById(self):
        self.client.post(
            "/api/analyze/url",
            json={"url": "https://test.com"},
        )
        entries = self.client.get("/api/history").json()["entries"]
        entryId = entries[0]["id"]

        resp = self.client.get(f"/api/history/{entryId}")
        assert resp.status_code == 200
        assert resp.json()["id"] == entryId

    def test_getHistoryEntryNotFound(self):
        resp = self.client.get("/api/history/non-existent-id")
        assert resp.status_code == 404

    def test_deleteHistoryEntry(self):
        self.client.post(
            "/api/analyze/url",
            json={"url": "https://delete-me.com"},
        )
        entries = self.client.get("/api/history").json()["entries"]
        entryId = entries[0]["id"]

        resp = self.client.delete(f"/api/history/{entryId}")
        assert resp.status_code == 200
        assert resp.json()["deleted"] is True

        assert self.client.get(f"/api/history/{entryId}").status_code == 404

    def test_deleteHistoryEntryNotFound(self):
        resp = self.client.delete("/api/history/non-existent-id")
        assert resp.status_code == 404

    def test_clearHistory(self):
        for i in range(3):
            self.client.post(
                "/api/analyze/url",
                json={"url": f"https://url-{i}.com"},
            )
        resp = self.client.delete("/api/history")
        assert resp.status_code == 200
        data = resp.json()
        assert data["deleted"] is True
        assert data["count"] == 3
        assert self.client.get("/api/history").json()["total"] == 0

    def test_historyPagination(self):
        for i in range(5):
            self.client.post(
                "/api/analyze/url",
                json={"url": f"https://page-{i}.com"},
            )
        resp = self.client.get("/api/history?limit=2&offset=0")
        data = resp.json()
        assert len(data["entries"]) == 2
        assert data["total"] == 5

    def test_analyzeEmailSavesToHistory(self):
        self.client.post(
            "/api/analyze/email",
            json={
                "content": "Your account has been suspended",
                "subject": "Alert",
                "sender": "test@example.com",
            },
        )
        data = self.client.get("/api/history").json()
        assert data["total"] == 1
        assert data["entries"][0]["contentType"] == "email"

    def test_analyzeContentAutoSavesToHistory(self):
        self.client.post(
            "/api/analyze",
            json={"content": "Some text content", "contentType": "text"},
        )
        data = self.client.get("/api/history").json()
        assert data["total"] == 1

    def test_rootEndpointIncludesHistoryLink(self):
        resp = self.client.get("/api/")
        data = resp.json()
        assert "history" in data["endpoints"]
